# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osiris.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'osiris.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cosiris.proto\x12\x06osiris\x1a\x1cgoogle/protobuf/struct.proto\"J\n\x13RegistrationRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0f\n\x07os_info\x18\x03 \x01(\t\"&\n\x14RegistrationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"Q\n\x11HeartbeatResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12,\n\x0binstruction\x18\x02 \x01(\x0b\x32\x17.osiris.HiveInstruction\"2\n\x0fHiveInstruction\x12\r\n\x05query\x18\x01 \x01(\t\x12\x10\n\x08query_id\x18\x02 \x01(\t\"o\n\x0bQueryResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\'\n\x06result\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12%\n\x07summary\x18\x03 \x01(\x0b\x32\x14.osiris.QuerySummary\"0\n\x0cQuerySummary\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1f\n\rQueryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd5\x01\n\nAgentComms\x12\x45\n\x08Register\x12\x1b.osiris.RegistrationRequest\x1a\x1c.osiris.RegistrationResponse\x12@\n\tHeartbeat\x12\x18.osiris.HeartbeatRequest\x1a\x19.osiris.HeartbeatResponse\x12>\n\x10SendQueryResults\x12\x13.osiris.QueryResult\x1a\x15.osiris.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osiris_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONREQUEST']._serialized_start=54
  _globals['_REGISTRATIONREQUEST']._serialized_end=128
  _globals['_REGISTRATIONRESPONSE']._serialized_start=130
  _globals['_REGISTRATIONRESPONSE']._serialized_end=168
  _globals['_HEARTBEATREQUEST']._serialized_start=170
  _globals['_HEARTBEATREQUEST']._serialized_end=206
  _globals['_HEARTBEATRESPONSE']._serialized_start=208
  _globals['_HEARTBEATRESPONSE']._serialized_end=289
  _globals['_HIVEINSTRUCTION']._serialized_start=291
  _globals['_HIVEINSTRUCTION']._serialized_end=341
  _globals['_QUERYRESULT']._serialized_start=343
  _globals['_QUERYRESULT']._serialized_end=454
  _globals['_QUERYSUMMARY']._serialized_start=456
  _globals['_QUERYSUMMARY']._serialized_end=504
  _globals['_QUERYRESPONSE']._serialized_start=506
  _globals['_QUERYRESPONSE']._serialized_end=537
  _globals['_AGENTCOMMS']._serialized_start=540
  _globals['_AGENTCOMMS']._serialized_end=753
# @@protoc_insertion_point(module_scope)
