# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import osiris_pb2 as osiris__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in osiris_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentCommsStub(object):
    """Service de communication entre l'agent et le Hive
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/osiris.AgentComms/Register',
                request_serializer=osiris__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=osiris__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/osiris.AgentComms/Heartbeat',
                request_serializer=osiris__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=osiris__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.SendQueryResults = channel.unary_unary(
                '/osiris.AgentComms/SendQueryResults',
                request_serializer=osiris__pb2.QueryResult.SerializeToString,
                response_deserializer=osiris__pb2.QueryResponse.FromString,
                _registered_method=True)


class AgentCommsServicer(object):
    """Service de communication entre l'agent et le Hive
    """

    def Register(self, request, context):
        """Enregistrement de l'agent et heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat et réception d'instructions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendQueryResults(self, request, context):
        """Envoi des résultats de requête
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentCommsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=osiris__pb2.RegistrationRequest.FromString,
                    response_serializer=osiris__pb2.RegistrationResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=osiris__pb2.HeartbeatRequest.FromString,
                    response_serializer=osiris__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SendQueryResults': grpc.unary_unary_rpc_method_handler(
                    servicer.SendQueryResults,
                    request_deserializer=osiris__pb2.QueryResult.FromString,
                    response_serializer=osiris__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'osiris.AgentComms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('osiris.AgentComms', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentComms(object):
    """Service de communication entre l'agent et le Hive
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osiris.AgentComms/Register',
            osiris__pb2.RegistrationRequest.SerializeToString,
            osiris__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osiris.AgentComms/Heartbeat',
            osiris__pb2.HeartbeatRequest.SerializeToString,
            osiris__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendQueryResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/osiris.AgentComms/SendQueryResults',
            osiris__pb2.QueryResult.SerializeToString,
            osiris__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
